### ISSUE TITLE
缺少对C++动态链接可执行程序的支持

### ISSUE THREAD

**Issue by YXalix** [Arceos-monolithic/Starry#21]
```c++
#include <iostream>

int main() {
    std::cout << "Hello, World!" << std::endl;
    return 0;
}
```
对于上述简单的hello world C++程序, 编译后需要依赖`libstdc++.so.6`, `libgcc_s.so.1`, `libc.so`三个动态库
```
nashzhou@smilinnet:~/code/Starry$ readelf -d test

Dynamic section at offset 0xe00 contains 27 entries:
  标记        类型                         名称/值
 0x0000000000000001 (NEEDED)             共享库：[libstdc++.so.6]
 0x0000000000000001 (NEEDED)             共享库：[libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             共享库：[libc.so]
```
当Starry运行这个C++程序test时, 会出现下述在重定向时发生的错误
```
Error relocating /lib/libstdc++.so.6: __floatunditf: symbol not found
Error relocating /lib/libstdc++.so.6: _Unwind_GetRegionStart: symbol not found
Error relocating /lib/libstdc++.so.6: _Unwind_GetTextRelBase: symbol not found
Error relocating /lib/libstdc++.so.6: _Unwind_RaiseException: symbol not found
```
而且我们能够查到
```
nashzhou@smilinnet:~/code/Starry$ nm ~/dev/riscv64-linux-musl/riscv64-linux-musl/lib/libgcc_s.so.1 | grep __floatunditf
00000000000096a2 T __floatunditf

nashzhou@smilinnet:~/code/Starry$ nm ~/dev/riscv64-linux-musl/riscv64-linux-musl/lib/libstdc++.so.6 | grep __floatunditf
                 U __floatunditf@@GCC_4.2.0
```

`__floatunditf`在`libgcc_s.so.1`中, 而且`libstdc++.so.6`依赖于`libgcc_s.so.1`, 但是在重定向的时候却说`__floatunditf: symbol not found`

**Comment by Azure-stars** [comment]
不过我本地编译这段代码的时候，得到的可执行文件执行 `readelf` 得到的内容如下：
```bash
$ readelf -d main                                                                                                                           ─╯

Dynamic section at offset 0x2d90 contains 28 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000000c (INIT)               0x1000
```
这里并没有依赖于`libgcc_s.so.1`，我的 g++ 版本为`x86_64-linux-gnu.11.4.0`，因此并不能完全确定是否解决了这个问题

**Comment by Azure-stars** [comment]
> 不过我本地编译这段代码的时候，得到的可执行文件执行 `readelf` 得到的内容如下：
> 
> ```shell
> $ readelf -d main                                                                                                                           ─╯
> 
> Dynamic section at offset 0x2d90 contains 28 entries:
>   Tag        Type                         Name/Value
>  0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
>  0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
>  0x000000000000000c (INIT)               0x1000
> ```
> 
> 这里并没有依赖于`libgcc_s.so.1`，我的 g++ 版本为`x86_64-linux-gnu.11.4.0`，因此并不能完全确定是否解决了这个问题

这里的编译指令是简单的 `g++ test.cpp -o main`

**Comment by yfblock** [comment]
> ```c++
> #include <iostream>
> 
> int main() {
>     std::cout << "Hello, World!" << std::endl;
>     return 0;
> }
> ```
> 
> 对于上述简单的hello world C++程序, 编译后需要依赖`libstdc++.so.6`, `libgcc_s.so.1`, `libc.so`三个动态库
> 
> ```
> nashzhou@smilinnet:~/code/Starry$ readelf -d test
> 
> Dynamic section at offset 0xe00 contains 27 entries:
>   标记        类型                         名称/值
>  0x0000000000000001 (NEEDED)             共享库：[libstdc++.so.6]
>  0x0000000000000001 (NEEDED)             共享库：[libgcc_s.so.1]
>  0x0000000000000001 (NEEDED)             共享库：[libc.so]
> ```
> 
> 当Starry运行这个C++程序test时, 会出现下述在重定向时发生的错误
> 
> ```
> Error relocating /lib/libstdc++.so.6: __floatunditf: symbol not found
> Error relocating /lib/libstdc++.so.6: _Unwind_GetRegionStart: symbol not found
> Error relocating /lib/libstdc++.so.6: _Unwind_GetTextRelBase: symbol not found
> Error relocating /lib/libstdc++.so.6: _Unwind_RaiseException: symbol not found
> ```
> 
> 而且我们能够查到
> 
> ```
> nashzhou@smilinnet:~/code/Starry$ nm ~/dev/riscv64-linux-musl/riscv64-linux-musl/lib/libgcc_s.so.1 | grep __floatunditf
> 00000000000096a2 T __floatunditf
> 
> nashzhou@smilinnet:~/code/Starry$ nm ~/dev/riscv64-linux-musl/riscv64-linux-musl/lib/libstdc++.so.6 | grep __floatunditf
>                  U __floatunditf@@GCC_4.2.0
> ```
> 
> `__floatunditf`在`libgcc_s.so.1`中, 而且`libstdc++.so.6`依赖于`libgcc_s.so.1`, 但是在重定向的时候却说`__floatunditf: symbol not found`

如果是使用 musl 编译的话，这个问题是因为 musl 在使用多个动态链接库的时候会使用 st_dev 和 st_ino 这两个作为标识，在加载阶段会判断时候加载过这个文件，如果加载过就不会再加载了。相关代码：https://github.com/bminor/musl/blob/4a16ddf53e7c634169d0a649782f8a724611f263/ldso/dynlink.c#L1172-L1182

所以问题就是加载过 libgcc 后将 st_dev 和 st_ino 进行保存，由于 Starry 的 fs 的问题，st_dev 和 st_ino 的值都为 0，所以再次加载libstdc++的时候会认为这个文件已经加载过了，但是事实是没有加载过，所以会找不到符号。

**Comment by Azure-stars** [comment]
> > ```c++
> > #include <iostream>
> > 
> > int main() {
> >     std::cout << "Hello, World!" << std::endl;
> >     return 0;
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 对于上述简单的hello world C++程序, 编译后需要依赖`libstdc++.so.6`, `libgcc_s.so.1`, `libc.so`三个动态库
> > ```
> > nashzhou@smilinnet:~/code/Starry$ readelf -d test
> > 
> > Dynamic section at offset 0xe00 contains 27 entries:
> >   标记        类型                         名称/值
> >  0x0000000000000001 (NEEDED)             共享库：[libstdc++.so.6]
> >  0x0000000000000001 (NEEDED)             共享库：[libgcc_s.so.1]
> >  0x0000000000000001 (NEEDED)             共享库：[libc.so]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 当Starry运行这个C++程序test时, 会出现下述在重定向时发生的错误
> > ```
> > Error relocating /lib/libstdc++.so.6: __floatunditf: symbol not found
> > Error relocating /lib/libstdc++.so.6: _Unwind_GetRegionStart: symbol not found
> > Error relocating /lib/libstdc++.so.6: _Unwind_GetTextRelBase: symbol not found
> > Error relocating /lib/libstdc++.so.6: _Unwind_RaiseException: symbol not found
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 而且我们能够查到
> > ```
> > nashzhou@smilinnet:~/code/Starry$ nm ~/dev/riscv64-linux-musl/riscv64-linux-musl/lib/libgcc_s.so.1 | grep __floatunditf
> > 00000000000096a2 T __floatunditf
> > 
> > nashzhou@smilinnet:~/code/Starry$ nm ~/dev/riscv64-linux-musl/riscv64-linux-musl/lib/libstdc++.so.6 | grep __floatunditf
> >                  U __floatunditf@@GCC_4.2.0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `__floatunditf`在`libgcc_s.so.1`中, 而且`libstdc++.so.6`依赖于`libgcc_s.so.1`, 但是在重定向的时候却说`__floatunditf: symbol not found`
> 
> 如果是使用 musl 编译的话，这个问题是因为 musl 在使用多个动态链接库的时候会使用 st_dev 和 st_ino 这两个作为标识，在加载阶段会判断时候加载过这个文件，如果加载过就不会再加载了。相关代码：https://github.com/bminor/musl/blob/4a16ddf53e7c634169d0a649782f8a724611f263/ldso/dynlink.c#L1172-L1182
> 
> 所以问题就是加载过 libgcc 后将 st_dev 和 st_ino 进行保存，由于 Starry 的 fs 的问题，st_dev 和 st_ino 的值都为 0，所以再次加载libstdc++的时候会认为这个文件已经加载过了，但是事实是没有加载过，所以会找不到符号。

当前 Starry 的 fs 默认 st_dev 为 1， st_ino 会为每一个文件分配一个值，应该是解决了这个问题
